# Generated by Django 4.2.7 on 2023-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Image/NoImage/noimage.jpg', upload_to='Image'),
        ),
    ]
